// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double rand = 0;
		double over_05_count = 0;
		double ratio = 0.0;

		for (int i = 0; i < n; i++){
			rand = Math.random();
			if (rand > 0.5){
				over_05_count++;
			}
		}


		System.out.println("> 0.5: " + over_05_count + " times");
		System.out.println("<= 0.5: " + (n-over_05_count) + " times");

		if (over_05_count != 0){
			ratio = over_05_count/(n-over_05_count);
			System.out.println(ratio);
		}

		


	}
}
